version: "3.9"

services:
  django:
    build: 
      context: backend
      dockerfile: Dockerfile
    command: sh -c "pip install -r requirements.txt &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_NAME=db_copybase
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db

  vue:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./frontend/src:/app/src

  db:
    image: postgres
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data

    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_HOST: db
      POSTGRES_DB: db_copybase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  db:
    driver: local