# Generated by Django 4.2.4 on 2024-03-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilha',
            name='data_envio_planilha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
