# Generated by Django 4.2.4 on 2024-03-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranca', '0002_alter_planilha_data_envio_planilha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('trial cancelado', 'Trial cancelado'), ('atrasada', 'Atrasada'), ('upgrade', ' Upgrade')], default='ativa', max_length=50),
        ),
    ]
