# Generated by Django 4.2.4 on 2023-08-08 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descricao')),
                ('url', models.URLField(verbose_name='Url')),
                ('urlToImage', models.URLField(verbose_name='Url imagem')),
                ('publishedAt', models.DateTimeField(verbose_name='Publicado em')),
                ('content', models.TextField(verbose_name='Conteudo')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='artigos.editora')),
            ],
        ),
    ]
