# Generated by Django 4.2.4 on 2023-08-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descricao')),
            ],
        ),
        migrations.AlterField(
            model_name='artigo',
            name='author',
            field=models.CharField(max_length=200, null=True, verbose_name='Autor'),
        ),
    ]
